[project]
name = "fraud-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Selma Karagøz", email = "selma.krgz@outlook.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fg-data-profiling>=4.19.1",
    "scikit-learn>=1.9.1",
    "setuptools<81",
    "xgboost>=3.4.1",
]

[project.scripts]
fraud-detection = "fraud_detection:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
